services:
  postgresql-b:
    image: postgres:14
    container_name: postgresql_b
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    volumes:
      - ./init/postgresql-init.sql:/docker-entrypoint-initdb.d/init.sql

  postgresql-b1:
    image: postgres:14
    container_name: postgresql_b1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shard1
    ports:
      - "5433:5432"
    volumes:
      - ./init/postgresql-init-shard.sql:/docker-entrypoint-initdb.d/init.sql

  postgresql-b2:
    image: postgres:14
    container_name: postgresql_b2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shard2
    ports:
      - "5434:5432"
    volumes:
      - ./init/postgresql-init-shard.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    build: ./php
    container_name: php_sharding
    volumes:
      - ./php:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000